# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 1.3.2
maven_group = net.countered.smoothf5
archives_name = smooth_f5
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.3

# Dependencies
architectury_api_version = 22.0.2
fabric_loader_version = 0.19.5
fabric_api_version = 0.161.0+26.3
neoforge_version = 26.3.0.7-beta

midnightlib_version_neoforge = 1.9.3.1+26.3-neoforge
midnightlib_version_fabric = 1.9.3+26.3-fabric
