modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "smooth_f5"
version = "${version}"
displayName = "Smooth F5"
authors = "Countered!"
description = '''
A mod for smoothing out the F5 camera view.
'''
logoFile = "icon.png"

[[dependencies.smooth_f5]]
modId = "neoforge"
type = "required"
versionRange = "[26.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smooth_f5]]
modId = "minecraft"
type = "required"
versionRange = "[26.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smooth_f5]]
modId = "architectury"
type = "required"
versionRange = "[22.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.smooth_f5]]
modId = "midnightlib"
type = "required"
versionRange = "[1.9.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "smooth_f5.mixins.json"
